/* Keyboard.cs
 *
 * Copyright © 2013 by Adam Hellberg and Brandon Scott
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 * Disclaimer: SwitchBlade is in no way affiliated
 * with Razer and/or any of its employees and/or licensors.
 * Adam Hellberg does not take responsibility for any harm caused, direct
 * or indirect, to any Razer peripherals via the use of SharpBlade.
 * 
 * "Razer" is a trademark of Razer USA Ltd.
 */


using System;
using Sharparam.SharpBlade.Native;

namespace Sharparam.SharpBlade.Razer.Events
{
    /// <summary>
    /// Keyboard event generated by Razer API when a key
    /// on the SBUI is pressed.
    /// Only the cleaned char/modifier are raised.
    /// </summary>
    public class KeyboardCharEventArgs : EventArgs
    { 
        /// <summary>
        /// Character pressed
        /// </summary>
        public readonly char KeyChar;
       
        /// <summary>
        /// Modifier key applied during character press
        /// </summary>
        /// 
        public readonly string KeyModifier;

        internal KeyboardCharEventArgs(char keyChar, string keyModifier)
        {
            KeyChar = keyChar;
            KeyModifier = keyModifier;
        }
              
    }
    /// <summary>
    /// Handler delegate for keyboard char event.
    /// </summary>
    /// <param name="sender">Object that threw the event.</param>
    /// <param name="e">Event arguments.</param>
    public delegate void KeyboardCharEventHandler(object sender, KeyboardCharEventArgs e);
}
