language: c

notifications:
  irc:
    channels:
      - "irc.kottnet.net#F16Gaming"
    template:
      - "travis build %{build_number} (%{branch} - %{commit} - %{author}): %{message} #{build_url}"
    on_success: change
    on_failure: always

install:
  - sudo apt-get install mono-devel mono-gmcs

script:
  - xbuild TravisCI.proj
