// <auto-generated />

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Sharparam.SwitchBladeSteam")]
[assembly: AssemblyDescription("Library providing native and logging functions to other SBS components.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("F16Gaming")]
[assembly: AssemblyProduct("Sharparam.SwitchBladeSteam")]
[assembly: AssemblyCopyright("Copyright © 2013 by Adam Hellberg and Brandon Scott.")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("2a168fde-01f2-48df-951f-8d521920de05")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0 Stable")]
