// ---------------------------------------------------------------------------------------
// <copyright file="KeyboardRawEventArgs.cs" company="SharpBlade">
//     Copyright © 2013-2014 by Adam Hellberg and Brandon Scott.
//
//     Permission is hereby granted, free of charge, to any person obtaining a copy of
//     this software and associated documentation files (the "Software"), to deal in
//     the Software without restriction, including without limitation the rights to
//     use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
//     of the Software, and to permit persons to whom the Software is furnished to do
//     so, subject to the following conditions:
//
//     The above copyright notice and this permission notice shall be included in all
//     copies or substantial portions of the Software.
//
//     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
//     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
//     CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//     Disclaimer: SharpBlade is in no way affiliated with Razer and/or any of
//     its employees and/or licensors. Adam Hellberg and/or Brandon Scott do not
//     take responsibility for any harm caused, direct or indirect, to any Razer
//     peripherals via the use of SharpBlade.
//
//     "Razer" is a trademark of Razer USA Ltd.
// </copyright>
// ---------------------------------------------------------------------------------------

using System;

using SharpBlade.Annotations;

namespace SharpBlade.Events
{
    /// <summary>
    /// Keyboard event generated by Razer API when a key
    /// on the SBUI is pressed.
    /// All parameters exposed as is.
    /// </summary>
    public class KeyboardRawEventArgs : EventArgs
    {
        /// <summary>
        /// Data of each type.
        /// </summary>
        private readonly UIntPtr _data;

        /// <summary>
        /// Modifiers applied during press.
        /// </summary>
        private readonly IntPtr _modifiers;

        /// <summary>
        /// The type of event (KeyUp, Char, KeyDown).
        /// </summary>
        private readonly uint _eventType;

        /// <summary>
        /// Initializes a new instance of the <see cref="KeyboardRawEventArgs" /> class.
        /// </summary>
        /// <param name="eventType">Keyboard event type.</param>
        /// <param name="data">Data associated with the event.</param>
        /// <param name="modifiers">Active modifiers.</param>
        internal KeyboardRawEventArgs(uint eventType, UIntPtr data, IntPtr modifiers)
        {
            _eventType = eventType;
            _data = data;
            _modifiers = modifiers;
        }

        /// <summary>
        /// Gets the data associated with the keyboard event.
        /// </summary>
        [CLSCompliant(false)]
        [PublicAPI]
        public UIntPtr Data
        {
            get { return _data; }
        }

        /// <summary>
        /// Gets the modifiers applied during key press.
        /// </summary>
        [PublicAPI]
        public IntPtr Modifiers
        {
            get { return _modifiers; }
        }

        /// <summary>
        /// Gets the type of event (KeyUp, Char, KeyDown).
        /// </summary>
        [CLSCompliant(false)]
        [PublicAPI]
        public uint EventType
        {
            get { return _eventType; }
        }
    }
}
